---
# handlers file for roles/rpimonitor
- name: restart rpimonitor
  become: true
  service:
    name: rpimonitor
    state: restarted
- name: update apt
  become: true
  apt:
    update_cache: true
